# Generated by Django 6.0 on 2026-05-14 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Institution Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Institution Address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Institution Website')),
                ('phone_number', models.CharField(blank=True, null=True, verbose_name='Institution Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Institution Email Address')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Established Year')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['country', 'city', 'established_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Subject Name')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Subject Code')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.subject', verbose_name='Parent Subject')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
    ]
