# Generated by Django 6.0 on 2026-05-26 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['accepted', 'pending'])), fields=('student', 'course_obj'), name='enrollment_status_unique'),
        ),
    ]
