# Generated by Django 6.0 on 2026-05-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_enrollment_enrollment_status_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='enrollment_status_unique',
        ),
    ]
