# Generated by Django 6.0 on 2026-05-27 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_enrollment_enrollment_status_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'course_obj'), name='unique_pending_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('student', 'course_obj'), name='unique_accepted_enrollment'),
        ),
    ]
