# Generated by Django 6.0 on 2026-05-27 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_enrollment_unique_pending_enrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_pending_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_accepted_enrollment',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('status', 'accepted'), _connector='OR'), fields=('student', 'course_obj'), name='unique_pending_enrollment'),
        ),
    ]
